# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=cuckoofilter-cabi

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "DAKMwqxd7aKF8tIzY2yHL8zPA4JEJDpXuEoPNvQCNtXMwjvGd9DEI1bz6wMkeMikGPhqzRVNzLBKn1s4rruT5CGNziP/JzYp5q6w2+EDuzQvS3tot492OPBG751V3Wi7aId8xsy4OBYKN/yDB4+8G7kqIQxPTpLSr+FcbyK9Ts5z/fvFBBtFYQyJwPkIp23LzH/03+f0tYYwWySLgmYKlszL/UybAoGj9xNBIFU1wzbha3E1rrgUXjxX8FBt+Mt6PRnwdfe800P/bm5e5K9y1zm8eK1XJf6yiceqAf1Pr0wEkWib2U4HKz4dAAKZZpG50fVD/Xis61dmHB69XMWIRh3E6cMnfHBySxqcGiBdzL+L2DEIFZGIUDpsFJRotm8KJgq/v0eEqjsHHzP7gQZWS9In51QfSP2bjKqx6FXfjJ0jVIVq1QL1SzYqP55hcG0m89/0KCEr5n9SdtQFaiPxhSEgIrlobbahl2Hfl8XEpG/DOb+Eb3zS+MqtsIji47D3dx1iqyfM4kw9Npsz2VLyd2k0OUdQC4GUNlZjQkufu09Ve5z5I4GzxQRQpwMfCrtaswicLlU1o65/+SJZExaw5qyDoYsvX8PCfCi/03KJdJmR49C8vmky1hTQP8HYLaCHIWa6iVJKQDhUILIaiHOEb5cYbErFdKDPXiB44mw2Nwk="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
